import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'autogenerated',
      dirName: 'chapters',
    },
  ],
};

export default sidebars;
